### ISSUE TITLE
strcmp: return the wrong value.

### ISSUE THREAD

**Issue by xlmod** [lfalkau/kfs#39]
strcmp return the difference between the two pointer insteed of between the two charactere

do this:
`return s1 - s2;`

need to do this:
`return *s1 - *s2;`

**Comment by e2r3p13** [comment]
Feel free to patch it and open a PR

**Comment by e2r3p13** [comment]
Fixed in [58ecf79](https://github.com/lfalkau/kfs/commit/58ecf79a2be198cb293b65346f6b71fe141be8ca)
